name = "discord-oidc"
main = "src/workers.ts"
compatibility_date = "2023-08-01"

kv_namespaces = [
  { binding = "KV", id = "f991bfb383e9423caebbfe74e8d235fa", preview_id = "68d64988288b4ae59fcd0c0011aaf656" }
]

[triggers]
crons = ["0 */1 * * *"]

[vars]
DISCORD_CLIENT_ID="1304334505171095592"
REDIRECT_URL="https://iotinj09.cloudflareaccess.com/cdn-cgi/access/callback"
SERVERS_ROLE_CLAIMS=["752806346868654100"]
CACHE_ROLES=false
